name: egsim
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=25.2
  - pytorch=2.0.0
  - torchvision=0.15.0
  - torchaudio=2.0.0
  - pytorch-cuda=11.8
  - pip:
      - camtools==0.1.7
      - gsplat==1.0.0
      - kornia==0.8.1
      - matplotlib==3.7.1
      - numpy==1.24.2
      - open3d==0.19.0
      - opencv_contrib_python==4.9.0.80
      - opencv_python==4.9.0.80
      - opencv_python_headless==4.11.0.86
      - pandas==2.0.0
      - plyfile==1.1.3
      - pyquaternion==0.9.9
      - pyside6==6.9.2
      - pyside6_addons==6.9.2
      - pyside6_essentials==6.9.2
      - PyYAML==6.0.3
      - scipy==1.13.1