from dataclasses import dataclass
from models.basic.basic_class import BasicSensorInfo

@dataclass
class LidarInfo(BasicSensorInfo):
    vfov: list[float] = ...
    hfov: list[float] = ...
    width: int = ...
    height: int = ...