ATAT_ON: True
noise_bound: 0.2
max_r_for_ATAT: 5.0
num_sectors_for_ATAT: 20

num_iter: 3
num_lpr: 20
num_min_pts: 10
num_rings: 30
num_sectors: 108

sensor_height: 1.723
th_seeds: 0.4
th_dist: 0.3
max_range: 80.0
min_range: 2.7
uprightness_thr: 0.5
adaptive_seed_selection_margin: -1.1

using_global_thr: False
global_elevation_thr: 0.0

sensor_model: "HDL-64E"
elevation_thr: [0.523, 0.746, 0.879, 1.125]
flatness_thr: [0.0005, 0.000725, 0.001, 0.001]